version: '3'

services:
  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    command: bundle exec rails s -b 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  postgres_data:
